[window]
decorations = "none"
startup_mode = "Maximized"

[shell]
program = "ubuntu"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
key = "Insert"
action = "Paste"

[font]
size = 11.0

[font.normal]
family = "SauceCodePro Nerd Font"

# Colors (Gruvbox dark)
# Default colors
[colors.primary]
background = '0x282828'
foreground = '0xebdbb2'

# Normal colors
[colors.normal]
black =   '0x282828'
red =     '0xcc241d'
green =   '0x98971a'
yellow =  '0xd79921'
blue =    '0x458588'
magenta = '0xb16286'
cyan =    '0x689d6a'
white =   '0xa89984'

# Bright colors
[colors.bright]
black =   '0x928374'
red =     '0xfb4934'
green =   '0xb8bb26'
yellow =  '0xfabd2f'
blue =    '0x83a598'
magenta = '0xd3869b'
cyan =    '0x8ec07c'
white =   '0xebdbb2'
