[window]
decorations = "none"
startup_mode = "Maximized"
#dynamic_padding = true
#padding = { x = 32, y = 32 }

[selection]
save_to_clipboard = true

[font]
size = 16.0

[font.normal]
family = "SauceCodePro Nerd Font Propo"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "I"
mods = "Command|Control"
action = "Paste"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "V"
mods = "Command"
chars = "\u001b\u0076"

[[keyboard.bindings]]
key = "Key1"
mods = "Command"
chars = "\u001a\u0031"

[[keyboard.bindings]]
key = "Key2"
mods = "Command"
chars = "\u001a\u0032"

[[keyboard.bindings]]
key = "Key3"
mods = "Command"
chars = "\u001a\u0033"

[[keyboard.bindings]]
key = "Key4"
mods = "Command"
chars = "\u001a\u0034"

[[keyboard.bindings]]
key = "Key5"
mods = "Command"
chars = "\u001a\u0035"

[[keyboard.bindings]]
key = "Key6"
mods = "Command"
chars = "\u001a\u0036"

[[keyboard.bindings]]
key = "Key7"
mods = "Command"
chars = "\u001a\u0037"

[[keyboard.bindings]]
key = "Key8"
mods = "Command"
chars = "\u001a\u0038"

[[keyboard.bindings]]
key = "Key9"
mods = "Command"
chars = "\u001a\u0039"

# Colors (Gruvbox dark)
# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
# soft contrast background = = '#32302f'
background = '#282828'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
#black =   '#282828'
black =   '#1d2021'
red =     '#cc241d'
green =   '#98971a'
yellow =  '#d79921'
blue =    '#458588'
magenta = '#b16286'
cyan =    '#689d6a'
white =   '#a89984'

# Bright colors
[colors.bright]
black =   '#928374'
red =     '#fb4934'
green =   '#b8bb26'
yellow =  '#fabd2f'
blue =    '#83a598'
magenta = '#d3869b'
cyan =    '#8ec07c'
white =   '#ebdbb2'
