[window]
decorations = "none"
startup_mode = "Maximized"

[selection]
save_to_clipboard = true

[[keyboard.bindings]]
#key = "Insert"
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "I"
mods = "Command|Control"
action = "Paste"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "V"
mods = "Command"
chars = "\u001b\u0076"

[[keyboard.bindings]]
key = "Key1"
mods = "Command"
chars = "\u001a\u0031"

[[keyboard.bindings]]
key = "Key2"
mods = "Command"
chars = "\u001a\u0032"

[[keyboard.bindings]]
key = "Key3"
mods = "Command"
chars = "\u001a\u0033"

[[keyboard.bindings]]
key = "Key4"
mods = "Command"
chars = "\u001a\u0034"

[[keyboard.bindings]]
key = "Key5"
mods = "Command"
chars = "\u001a\u0035"

[[keyboard.bindings]]
key = "Key6"
mods = "Command"
chars = "\u001a\u0036"

[[keyboard.bindings]]
key = "Key7"
mods = "Command"
chars = "\u001a\u0037"

[[keyboard.bindings]]
key = "Key8"
mods = "Command"
chars = "\u001a\u0038"

[[keyboard.bindings]]
key = "Key9"
mods = "Command"
chars = "\u001a\u0039"

[font]
size = 16.0

[font.normal]
family = "SauceCodePro Nerd Font Propo"

# Colors (Gruvbox dark)
# Default colors
[colors.primary]
background = '0x282828'
foreground = '0xebdbb2'

# Normal colors
[colors.normal]
black =   '0x282828'
red =     '0xcc241d'
green =   '0x98971a'
yellow =  '0xd79921'
blue =    '0x458588'
magenta = '0xb16286'
cyan =    '0x689d6a'
white =   '0xa89984'

# Bright colors
[colors.bright]
black =   '0x928374'
red =     '0xfb4934'
green =   '0xb8bb26'
yellow =  '0xfabd2f'
blue =    '0x83a598'
magenta = '0xd3869b'
cyan =    '0x8ec07c'
white =   '0xebdbb2'
