#!/bin/sh /etc/rc.common

START=50
USE_PROCD=1
 
start_service() {        
	procd_open_instance

	procd_set_param command /opt/deploy/gost/pro/gost -C /opt/deploy/gost/cfg/gost.yml
	procd_set_param pidfile /opt/deploy/gost/run/gost.pid
	procd_set_param term_timeout 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn 60 10 10

	procd_close_instance
}                 
