syntax on

set encoding=utf-8

set number
"set relativenumber
set nowrap
set hlsearch
set incsearch
set showcmd
set autoindent
set cindent
set copyindent
set smartindent
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
set smarttab
set scrolloff=3

set updatetime=100
set mouse=

"set backup
set backupext=.bakvim
set backspace=indent,eol,start

set wildmode=longest,list,full
set wildmenu

set fileencodings=utf-8,gb18030,gbk,gb2312,big5

set signcolumn=yes

set laststatus=2
let g:airline_theme = 'powerlineish'
let g:airline_powerline_fonts = 1


" Font
set guifont=Source\ Code\ Pro

nnoremap ZZ <nop>

autocmd BufReadPost *
\ if line("'\"") > 0 && line("'\"") <= line("$") |
\ exe "normal g`\""|
\ endif


autocmd FileType python setlocal shiftwidth=4 tabstop=4 softtabstop=4
autocmd FileType javascript setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType css,sass,scss setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType sh setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType ruby setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType html setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType yaml,json,toml,helm setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType text,markdown,rst,tex setlocal textwidth=120

"autocmd FileType python let b:coc_suggest_disable=1

" taglist options
let Tlist_Show_One_File = 1
let Tlist_Exit_OnlyWindow = 1
let Tlist_Use_Right_Window = 1
"let Tlist_WinWidth = 20

" ale options
let g:airline#extensions#ale#enabled = 1
let g:ale_sign_column_always = 0
let g:ale_lint_on_enter = 1
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_text_changed = 'never'
let g:ale_linters = {
\   'go': ['gofmt', 'golint', 'govet', 'gobuild'],
\}
let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'javascript': ['prettier', 'eslint'],
\   'typescript': ['prettier'],
\   'python': ['black', 'isort'],
\   'rust': ['rustfmt'],
\}
let g:ale_fix_on_save = 1
let g:ale_sign_error = 'X'
let g:ale_sign_warning = '!'
"let g:ale_echo_msg_error_str = 'E'
"let g:ale_echo_msg_warning_str = 'W'
let g:ale_echo_msg_format = '[%severity%](%linter%) %code%: %s'
let g:ale_python_mypy_options = '--ignore-missing-imports'

" delimitMate options
let delimitMate_expand_cr = 1
let delimitMate_expand_space = 1


" load coc settings
try
    source ~/.vimrc_coc
catch
    " It's OK
endtry


" vim-plug  https://github.com/junegunn/vim-plug
" Find plugins in http://vimawesome.com/
" Install vim-plug with following command:
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
call plug#begin('~/.vim/plugged')

Plug 'altercation/vim-colors-solarized'
Plug 'morhetz/gruvbox'
"Plug 'powerline/fonts'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

"Plug 'ervandew/supertab'
Plug 'raimondi/delimitmate'

"Plug 'airblade/vim-gitgutter'
"Plug 'mhinz/vim-signify'
"Plug 'w0rp/ale'
"Plug 'valloric/youcompleteme'
"Plug 'taglist.vim'
"Plug 'davidhalter/jedi-vim'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'sebdah/vim-delve'

Plug 'fatih/vim-go'
Plug 'rust-lang/rust.vim'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'tpope/vim-haml'
Plug 'martinda/jenkinsfile-vim-syntax'
Plug 'towolf/vim-helm'

call plug#end()


" Color
if has('gui_running')
    set background=light
else
    set background=dark
endif
"colorscheme solarized
colorscheme gruvbox
