syntax on

set number
set nowrap
set hlsearch
set incsearch
set showcmd
set autoindent
set cindent
set copyindent
set smartindent
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
set smarttab
set scrolloff=3
"set backup
set backupext=.bakvim
set backspace=indent,eol,start

set fileencodings=utf-8,gb18030,gbk,gb2312,big5

set laststatus=2
let g:airline_theme = 'powerlineish'
let g:airline_powerline_fonts = 1


" Font
set guifont=Source\ Code\ Pro

" Color
if has('gui_running')
    set background=light
else
    set background=dark
endif
colorscheme solarized

autocmd BufReadPost *
\ if line("'\"") > 0 && line("'\"") <= line("$") |
\ exe "normal g`\""|
\ endif


autocmd FileType python setlocal shiftwidth=4 tabstop=4 softtabstop=4
autocmd FileType ruby setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType yaml,json,toml setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType markdown setlocal textwidth=72


" taglist options
let Tlist_Show_One_File = 1
let Tlist_Exit_OnlyWindow = 1
let Tlist_Use_Right_Window = 1
"let Tlist_WinWidth = 20


" vim-plug  https://github.com/junegunn/vim-plug
" Find out plugins in  http://vimawesome.com/
" Install vim-plug with following command:
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
call plug#begin('~/.vim/plugged')

Plug 'valloric/youcompleteme'
"Plug 'ervandew/supertab'
"Plug 'taglist.vim'

Plug 'altercation/vim-colors-solarized'
"Plug 'powerline/fonts'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

call plug#end()
