syntax on

set number
set nowrap
set hlsearch
set incsearch
set showcmd
set autoindent
set cindent
set copyindent
set smartindent
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
set smarttab
set scrolloff=3
"set backup
set backupext=.bakvim

set fileencodings=utf-8,gb18030,gbk,gb2312,big5

autocmd BufReadPost *
\ if line("'\"") > 0 && line("'\"") <= line("$") |
\ exe "normal g`\""|
\ endif

let Tlist_Show_One_File = 1            "不同时显示多个文件的tag，只显示当前文件的
let Tlist_Exit_OnlyWindow = 1          "如果taglist窗口是最后一个窗口，则退出vim
let Tlist_Use_Right_Window = 1         "在右侧窗口中显示taglist窗口
"let Tlist_WinWidth = 20
